# Generated by Django 3.0.1 on 2019-12-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='blog.Blog'),
        ),
    ]
